#!/bin/sh -ex

. run-swtpm

IMAGE_DIR=tmp-glibc/deploy/images/intel-corei7-64
truncate -s 4G $IMAGE_DIR/my-installed-image-intel-corei7-64.wic
cp $IMAGE_DIR/refkit-installer-image-intel-corei7-64.qemuboot.conf $IMAGE_DIR/my-installed-image-intel-corei7-64.qemuboot.conf

runqemu serial nographic refkit-installer-image wic intel-corei7-64 "qemuparams=-drive if=virtio,file=$IMAGE_DIR/my-installed-image-intel-corei7-64.wic,format=raw -tpmdev unixio-tpm,id=tpm0,path=${SWTPM_SERVER_SOCKET},ctrl-path=${SWTPM_CTRL_SOCKET} -device tpm-tis,tpmdev=tpm0" ovmf
